
project_id = "uejymkggevuvuerldzhv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
enabled = true
serve_port = 54325

[functions.submit-form]
verify_jwt = false
include_cross_origin_headers = true
max_timeout = 15

[functions.approve-submission]
verify_jwt = false
include_cross_origin_headers = true
max_timeout = 15

[functions.process-data]
verify_jwt = false
include_cross_origin_headers = true
max_timeout = 30

[functions.setup]
verify_jwt = false
include_cross_origin_headers = true
max_timeout = 10

[functions.test-pipeline]
verify_jwt = false
include_cross_origin_headers = true
max_timeout = 60

[functions.test-g11-5aw]
verify_jwt = false
include_cross_origin_headers = true
max_timeout = 30

[functions.auto-process-batch]
verify_jwt = false
include_cross_origin_headers = true
max_timeout = 60

[vector]
enabled = false
port = 54326
