
project_id = "uejymkggevuvuerldzhv"

[functions.process-addresses]
verify_jwt = false

[functions.notify-admin]
verify_jwt = false

[functions.process-approval]
verify_jwt = false

[functions.setup]
verify_jwt = false

[storage.pending-uploads]
public = false
allowed_mime_types = ["text/csv", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
file_size_limit = 5242880

[storage.approved-uploads]
public = false
allowed_mime_types = ["text/csv", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
file_size_limit = 5242880
