
# This file controls the configuration of the Lovable backed by Supabase project.
project_id = "process-addresses"

# Email sender function debug logging configuration
[global.env_variables]
LOG_LEVEL = "INFO"

# Function configurations
[functions.setup]
verify_jwt = false

[functions.email-sender]
verify_jwt = false

[functions.process-addresses]
verify_jwt = false

[functions.notify-admin]
verify_jwt = false

[functions.process-approval]
verify_jwt = false

