name: Find and Replace Text

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  find-and-replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Find and Replace
      uses: replicate/find-and-replace-action@v1
      with:
        find: "supabase.functions.invoke('process-addresses'" # The text to find
        replace: "supabase.functions.invoke('notify-admin'"   # The text to replace it with
        files: "**/*.js"                                     # Files to include (e.g., all JavaScript files)

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -am "Replace process-addresses with notify-admin"
        git push
