
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main  # Update to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 'latest'

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Deploy submit-form
        run: supabase functions deploy submit-form \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt

      - name: Deploy approve-submission
        run: supabase functions deploy approve-submission \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt

      - name: Deploy process-data
        run: supabase functions deploy process-data \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt
               
      - name: Deploy setup
        run: supabase functions deploy setup \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt

      - name: Deploy test-pipeline
        run: supabase functions deploy test-pipeline \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt

      - name: Output Deployed URLs
        run: |
          echo "Deployed URLs:"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/submit-form"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/approve-submission"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/process-data"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/setup"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/test-pipeline"
