name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - feat/csv-approval-workflow  # or main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: \${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "\$SUPABASE_ACCESS_TOKEN"

      - name: Deploy process-addresses
        run: supabase functions deploy process-addresses \\
               --project-ref uejymkgeevuvuerldzhv \\
               --no-verify-jwt
