
name: Deploy Test Environment

on:
  push:
    branches:
      - test-env

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_VyxsOHe5OnNHCZuVvoIBnXof0taC/VIR[...]"
