
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main  # Update to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 'latest'

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Deploy process-addresses
        run: supabase functions deploy process-addresses \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt

      - name: Deploy notify-admin
        run: supabase functions deploy notify-admin \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt

      - name: Deploy process-approval
        run: supabase functions deploy process-approval \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt
               
      - name: Deploy setup
        run: supabase functions deploy setup \
               --project-ref uejymkggevuvuerldzhv \
               --no-verify-jwt

      - name: Output Deployed URLs
        run: |
          echo "Deployed URLs:"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/process-addresses"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/notify-admin"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/process-approval"
          echo "- https://uejymkggevuvuerldzhv.functions.supabase.co/setup"
