name: Find and Replace Text

on:
  workflow_dispatch:

jobs:
  find-and-replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "supabase.functions.invoke('process-addresses'"
        replace: "supabase.functions.invoke('notify-admin'"
        regex: false
        include: "**/*.js"
        fail_on_no_matches: false

    - name: Commit Changes to feature branch
      run: |
        git checkout -b replace-text-branch
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -am "Replace process-addresses with notify-admin"
        git push origin replace-text-branch
